name          'att-apacheconf'
version       '0.1.0'
source        'git.puppetlabs.net:seteam/attMiddleware/apacheconf'
author        'dgrstl'
license       'Apache 2.0'
summary       'AT&T QA Apache Configuration'
description   'Configure all necessary Apache HTTPD instances to support a given QA daemon'
project_page  ''

dependency 'puppetlabs/stdlib'
